### ISSUE TITLE
How to install mock-loader?

### ISSUE THREAD

**Issue by stefaneidelloth** [vejersele/mock-loader#3]
Do you have an example project that shows how to use mock-loader with karma and webpack?

mock-loader itself seems to be a CommonJs module and not an AMD module. 

=> Uncaught ReferenceError: module is not defined.

Related SO-Question:

https://stackoverflow.com/questions/57379078/how-to-mock-amd-module-dependencies-for-es6-unit-tests-with-karma-requirejs

**Comment by skrivle** [comment]
Hi There, I unfortunately don't have an example project for you. Just to give you some context, I've written this webpack plugin quite some time ago to help with the requirejs > webpack migration of a large project I was working on back then. We've only used this plugin very shortly since after the initial migration we converted the whole codebase to make use of ES6 modules. 

This loader is build to use with webpack 1, I'm not sure if it will work with newer versions of webpack. The loader is indeed a commonjs module since that is how you were supposed to create webpack plugins at the time. 

As far as I can remember, the only thing that you need to do is `npm install mock-loader` and webpack will automatically resolve modules using the loader when prefixed with `mock!`

https://devdocs.io/webpack~1/loaders

hope this helps!

**Comment by stefaneidelloth** [comment]
Thank you for the fast answer. How do you unit test and mock your ES6 modules? Is there a way to do it without translating it to ES5 with webpack?

**Comment by skrivle** [comment]
I honestly try to avoid having to mock entire modules. It might be better to pass the dependency as a constructor or function param instead of directly requiring it. This way mocking becomes easier since you don't have to bypass the whole module system. 

Anyway, I'm a big fan of Jest to run tests, and I know it provides a way to mock modules as well. Might be good to have a look: https://jestjs.io/docs/en/es6-class-mocks

cheers!
